name: "RELEASE ➕"
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "gituser@example.com"

      - name: Set Git remote URL
        run: git remote set-url origin https://semantic:${{ secrets.GITHUB_TOKEN }}@github.com/dtap001/gcl.git

      - name: Install dependencies
        run: npm ci

      - name: Versioning and Tagging
        run: |
          npx nx affected --target=version --base=last-release --parallel=1
          git tag -f last-release
          git push origin last-release --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
